# Generated by Django 3.2.24 on 2024-03-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0004_remove_party_opening_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='opening_stock',
            field=models.IntegerField(default=0),
        ),
    ]
