# Generated by Django 3.2.24 on 2024-03-19 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0005_party_opening_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='at_price',
        ),
    ]
