# Generated by Django 3.2.24 on 2024-03-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0007_party_at_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnotereference',
            name='credit_note',
        ),
        migrations.AddField(
            model_name='creditnote',
            name='reference_no',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
