# Generated by Django 3.2.25 on 2024-03-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0010_alter_creditnote_reference_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnotehistory',
            name='hist_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
