# Generated by Django 3.2.25 on 2024-03-28 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0011_alter_creditnotehistory_hist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='reference_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditnotehistory',
            name='credit_note_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.creditnote'),
        ),
        migrations.AlterField(
            model_name='creditnoteitem',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.creditnote'),
        ),
    ]
